### ISSUE TITLE
Duplicate types and missing transaction Deserialization

### ISSUE THREAD

**Issue by zees-dev** [gmosx/xrpl_sdk_rust#27]
Was planning to use this library to test an end-to-end example of transaction deserialization and verification.
Unfortunately have stumbled across a few hurdles:
- Duplicate struct declarations for the same types
  - I simply want to validate the serialization of a transaction works; specifically the the example [here](https://xrpl.org/serialization.html#examples):
    - unfortunately this requires deserializing the JSON string to the `xrpl_api::OfferCreateTransaction` struct (which implements serde's `Deserialize`), then using the `xrpl_types::OfferCreateTransaction` struct (which implements `Serializer`)
    - additionally, there isn't an API to convert `xrpl_api::OfferCreateTransaction` <-> `xrpl_types::OfferCreateTransaction` (i.e. a `From` trait) - hence a manual conversion must be done
- Missing implementation of a `Deserializer` trait
  - Looking deeper into the [serialization](https://xrpl.org/serialization.html) - seems like this isn't straightforward

Before trying to implement Deserialization; I was wondering if this implementation is already in the works?
Also are we planning to unify the multiple declarations for the transaction structs?

**Comment by gmosx** [comment]
Re conversion between xrpl_api/xrpl_types types, that might be an interesting feature for the future, I will keep a note.

What is the use case for deserializing an xrpl_types (core server) type?

**Comment by zees-dev** [comment]
> Re conversion between xrpl_api/xrpl_types types, that might be an interesting feature for the future, I will keep a note.
> 
> What is the use case for deserializing an xrpl_types (core server) type?

There are no canonical rust based xrpl client SDK implementations out there, this repo is the closest thing there is to that. 
Specifically we want to do on-chain signature verification - given a serialized transaction. 

The JavaScript SDK provides this functionality (signature verification), but unfortunately we cannot use JavaScript on-chain.
The chain we have is substrate based. There are additional requirements (i.e the code must be compilable to wasm32-unknown-unknown target) - but we will get to those later (might need to fork repo and put some functionality behind feature flags).

**Comment by zees-dev** [comment]
I have implemented support for deserialization (specifically for XUMM wallet based/signed transactions) here: https://github.com/futureversecom/xrpl-sdk-rust/pull/1
^ will be closing this issue.

Do let me know if you'd like me to PR the changes upstream.

**Comment by gmosx** [comment]
Yes, I would *love* to have a PR, thank you!

**Comment by gmosx** [comment]
I added some comments/nitpicks to your PR.

**Comment by zees-dev** [comment]
Thanks for the review; do let me know if you think we should remove the `Deserialize` and `Deserializer` traits; at the moment there is only a single implementation (which was initially inspired by [`xrpl.js`](https://github.com/XRPLF/xrpl.js/tree/main/packages/ripple-binary-codec#readme) deserializer).

On a sidenote, support for the the wasm32 compilation target is very useful (IMO) as it greatly increases code interoperability.
However not all crates support wasm32 (you can verify via `cargo check -p xrpl_binary_codec --target wasm32-unknown-unknown` for example)
^ I can remove this from the upstream PR if you'd like, but I will be keeping it in the fork (as it's required for on-chain transaction decoding and verification).

**Comment by zees-dev** [comment]
Opened PR here: https://github.com/gmosx/xrpl-sdk-rust/pull/30
feel free to leave any additional comments; will make changes accordingly!

**Comment by zees-dev** [comment]
Closing this issue - since has been addressed in https://github.com/gmosx/xrpl-sdk-rust/pull/30
