### ISSUE TITLE
Incomplete Transaction

### ISSUE THREAD

**Issue by vporton** [gmosx/xrpl_sdk_rust#7]
`xrpl_types::transaction::Transaction` does not have all the finds of some particular transaction types. For example, `Domain` from `AccountSet` transaction is missing.

The missing transaction fields are due to not finished work, aren't they?

Do you accept pull requests adding transaction fields?

**Comment by gmosx** [comment]
Yes, I am happy to accept PRs!

**Comment by vporton** [comment]
Instead of these PR, I implemented in my repository https://github.com/vporton/xrpl_async-rs zero-overhead code generation to describe transactions:
https://github.com/vporton/xrpl_async-rs/blob/main/src/txs/payment.rs

With my development a part of your software becomes outdated (however, I import your binary codec).

**Comment by gmosx** [comment]
OK, thanks for the heads-up. I will check what you have done, and maybe incorporate some good ideas.
